/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GuilangRuntimeModule extends AbstractGuilangRuntimeModule {
	override bindIQualifiedNameProvider() {
		return GuilangNameProvider
	}
}
