/*
 * generated by Xtext 2.16.0
 */
package org.sdu.mdsd.guilang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GuilangStandaloneSetup extends GuilangStandaloneSetupGenerated {

	def static void doSetup() {
		new GuilangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
